[hardware]
  model = "ZNB"
  address = 'TCPIP0::192.168.1.215::inst0::INSTR'
  attenuation = 80
  port = "S21"

[sample]
  name = "TEST"


[[measurement]]
  label = "test"
  output = "/home/ratiswu/liteVNA_test/test"

  IF_bandwidth = 1000
  power = -40
  repeat = 1
  [measurement.frequency]
    start = 3e9
    stop = 9e9
    points = 501