[hardware]
  model = "E5080B"
  address = 'TCPIP0::192.168.1.78::inst0::INSTR'
  attenuation = 80
  port = "S21"

[sample]
  name = "ITRI"


[[measurement]]

  IF_bandwidth = 1000
  power = 10
  
  [measurement.frequency]
    deltafre = 5e6
    resonator_fre = 4.5312e9
    points = 501

[[measurement]]

  IF_bandwidth = 1000
  power = 10
  
  [measurement.frequency]
    deltafre = 5e6
    resonator_fre = 4.6157e9
    points = 501